/**
 * importProducts.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Excel → MongoDB import pipeline for SHRI Enterprises catalogue.
 *
 * Prerequisites:
 *   1. Run: node seeders/seedCategories.js   (populates Category collection)
 *   2. Place catalogue_products.json in same dir (generated by export_catalogue.py)
 *      OR point XLSX_PATH env var to the raw .xlsx file and use the xlsx branch below.
 *
 * Usage:
 *   MONGO_URI=mongodb://localhost:27017/evwheels node scripts/importProducts.js
 *
 * Features:
 *   ✓ Upsert by name + category — safe to re-run; won't duplicate
 *   ✓ Category resolved by name → ObjectId
 *   ✓ Subcategory resolved by name + category → ObjectId (auto-created if missing)
 *   ✓ productType auto-detected from category name
 *   ✓ specs parsed from shortDescription (comma-separated key phrases)
 *   ✓ Slug auto-generated (deduped in model)
 *   ✓ Summary report at end
 * ─────────────────────────────────────────────────────────────────────────────
 */

import fs from "fs";
import path from "path";

import Product from "../models/Product.js";
import Category from "../models/Category.js";
import Subcategory from "../models/Subcategory.js";
import dotenv from "dotenv";
dotenv.config();
import mongoose from "mongoose";
import { fileURLToPath } from "url";

// Fix __dirname in ES modules
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// ─── Config ──────────────────────────────────────────────────────────────────
const MONGO_URI = process.env.MONGODB_URI;
console.log(MONGO_URI);

const DATA_FILE = path.join(__dirname, "..", "catalogue_products.json");

// ─── Helpers ─────────────────────────────────────────────────────────────────

/**
 * Detect product type from category name.
 * Extend this map as EV products are added.
 */
function detectProductType(categoryName) {
  const name = categoryName.toLowerCase();
  if (/electric|ev |battery|motor|controller|charger/.test(name))
    return "ev_part";
  if (/helmet|safety|glove|mask|reflector/.test(name)) return "safety";
  if (/tool|wrench|spanner|key|kit|maintenance/.test(name)) return "tool";
  if (
    /bag|holder|carrier|rack|lock|bell|horn|light|grip|tape|cover|stand/.test(
      name
    )
  )
    return "accessory";
  return "bicycle_part";
}

/**
 * Parse the "Description / Specs" field into a specs Map.
 * Handles comma-separated phrases like "Steel Shaft, Premium" or "3x7 Speed, Shimano"
 *
 * For structured attributes (Material, Size, Brand, etc.) we attempt to tag them.
 */
function parseSpecs(shortDesc) {
  if (!shortDesc || shortDesc === "Standard" || shortDesc === "nan") return {};

  const specs = {};
  const parts = shortDesc
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

  // Known brand names
  const BRANDS = [
    "Shimano",
    "Neco",
    "Kenli",
    "Pacific",
    "Maya",
    "DTO",
    "Bolids",
    "Beto",
    "Lema",
    "Prowheel",
    "Brutt",
    "Giant",
  ];

  // Known material keywords
  const MATERIALS = [
    "Steel",
    "Alloy",
    "Aluminium",
    "PVC",
    "Nylon",
    "Silicone",
    "ABS",
    "Rubber",
    "Carbon",
    "Magnesium",
  ];

  parts.forEach((part, i) => {
    const brandMatch = BRANDS.find((b) => part.includes(b));
    const matMatch = MATERIALS.find((m) =>
      part.toLowerCase().includes(m.toLowerCase())
    );

    if (brandMatch && !specs.brand) {
      specs.brand = brandMatch;
    } else if (matMatch && !specs.material) {
      specs.material = matMatch;
    } else if (/\d+\s*mm/.test(part) && !specs.size) {
      specs.size = part;
    } else if (/speed/i.test(part) && !specs.speeds) {
      specs.speeds = part;
    } else if (/\d+\s*(gm|gram)/i.test(part) && !specs.weight) {
      specs.weight = part;
    } else if (/pair/i.test(part)) {
      specs.packaging = specs.packaging
        ? specs.packaging + ", Pair"
        : "Pair";
    } else if (/box pack/i.test(part)) {
      specs.packaging = specs.packaging
        ? specs.packaging + ", Box Pack"
        : "Box Pack";
    } else if (/imported/i.test(part)) {
      specs.origin = "Imported";
    } else {
      // Generic: store as "spec_N"
      specs[`spec${i + 1}`] = part;
    }
  });

  return specs;
}

/**
 * Build tags array from name + subcategory for full-text search.
 */
function buildTags(product, categoryName) {
  const text = `${product.name} ${product.subcategory} ${categoryName} ${product.shortDescription}`;
  return [
    ...new Set(
      text
        .toLowerCase()
        .replace(/[^a-z0-9\s]/g, " ")
        .split(/\s+/)
        .filter((t) => t.length > 2)
    ),
  ];
}

// ─── Main ────────────────────────────────────────────────────────────────────
async function importProducts() {
  await mongoose.connect(MONGO_URI);
  console.log("✅ Connected to MongoDB\n");

  // Load category map: name → _id
  const categories = await Category.find({});
  const categoryMap = {};
  categories.forEach((c) => {
    categoryMap[c.name] = c._id;
  });
  console.log(`📂 Loaded ${categories.length} categories\n`);

  // Load subcategory map: "categoryName|subcategoryName" → _id
  // Auto-create missing subcategories
  const subcategories = await Subcategory.find({});
  const subcategoryMap = {};
  subcategories.forEach((s) => {
    const cat = categories.find((c) => c._id.equals(s.category));
    if (cat) {
      subcategoryMap[`${cat.name}|${s.name}`] = s._id;
    }
  });

  // Load product data
  const products = JSON.parse(fs.readFileSync(DATA_FILE, "utf-8"));
  console.log(`📦 Processing ${products.length} products...\n`);

  const stats = { inserted: 0, updated: 0, skipped: 0, errors: [] };

  for (const raw of products) {
    try {
      const categoryId = categoryMap[raw.category];
      if (!categoryId) {
        stats.errors.push({
          sno: raw.sno,
          reason: `Category not found: "${raw.category}"`,
        });
        continue;
      }

      // ── Resolve or create subcategory ──────────────────────
      let subcategoryId = null;

      if (raw.subcategory) {
        const subKey = `${raw.category}|${raw.subcategory}`;
        subcategoryId = subcategoryMap[subKey];

        if (!subcategoryId) {
          // Auto-create subcategory
          const newSub = await Subcategory.create({
            category: categoryId,
            name: raw.subcategory,
            isActive: true,
          });
          subcategoryId = newSub._id;
          subcategoryMap[subKey] = subcategoryId;
          console.log(`  ↳ Created subcategory: ${raw.subcategory}`);
        }
      }

      // If no subcategory, assign the category itself as a fallback
      // (subcategory is required in Product model)
      if (!subcategoryId) {
        // Create a subcategory matching the category name
        const subKey = `${raw.category}|${raw.category}`;
        subcategoryId = subcategoryMap[subKey];

        if (!subcategoryId) {
          const newSub = await Subcategory.create({
            category: categoryId,
            name: raw.category,
            isActive: true,
          });
          subcategoryId = newSub._id;
          subcategoryMap[subKey] = subcategoryId;
        }
      }

      const specs = parseSpecs(raw.shortDescription);
      const productType = detectProductType(raw.category);
      const tags = buildTags(raw, raw.category);

      const doc = {
        name: raw.name,
        shortDescription: raw.shortDescription || "",
        description: raw.description || raw.shortDescription || "",
        category: categoryId,
        subcategory: subcategoryId,
        brand: specs.brand || raw.brand || "",
        price: {
          base: raw.price || 0,
          gstPercent: 18,
          currency: "INR",
        },
        inventory: {
          stock: raw.stock || 0,
          moq: raw.moq || 1,
          boxQty: raw.boxQty || 1,
        },
        specs,
        tags,
        filterAttributes: [],
        isActive: true,
      };

      // Upsert by name + category — safe to re-run
      const existing = await Product.findOne({
        name: raw.name,
        category: categoryId,
      });

      if (existing) {
        // Preserve images and slug on re-import
        await Product.updateOne(
          { _id: existing._id },
          {
            $set: {
              ...doc,
              // Don't clobber existing slug if already set
              ...(existing.slug ? {} : {}),
            },
          }
        );
        stats.updated++;
      } else {
        await Product.create(doc);
        stats.inserted++;
      }

      process.stdout.write(
        `  [${raw.sno || "—"}] ${raw.name.slice(0, 50)}${raw.name.length > 50 ? "…" : ""}\n`
      );
    } catch (err) {
      stats.errors.push({ sno: raw.sno, reason: err.message });
    }
  }

  // ─── Report ────────────────────────────────────────────────────────────────
  console.log("\n" + "─".repeat(60));
  console.log("📊  IMPORT SUMMARY");
  console.log("─".repeat(60));
  console.log(`  ✅  Inserted : ${stats.inserted}`);
  console.log(`  🔄  Updated  : ${stats.updated}`);
  console.log(`  ⏭   Skipped  : ${stats.skipped}`);
  console.log(`  ❌  Errors   : ${stats.errors.length}`);
  if (stats.errors.length) {
    console.log("\n  Error details:");
    stats.errors.forEach((e) =>
      console.log(`    S.No ${e.sno}: ${e.reason}`)
    );
  }
  console.log("─".repeat(60));

  const total = await Product.countDocuments();
  console.log(`\n  Total products in DB: ${total}`);

  await mongoose.disconnect();
  console.log("\n✅ Done.");
}

importProducts().catch((err) => {
  console.error("❌ Import failed:", err);
  process.exit(1);
});
